select * from customer limit 20

--What is the Total revenue generated by male vs female customers
Select gender,SUM(purchase_amount) AS revenue
FROM customer 
GROUP BY gender

--Which customers use a discount but still spend more than avg purchase amount?

Select customer_id,purchase_amount
from customer
WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Which are top5 products with highest avg review rating?
Select item_purchased, ROUND(AVG(review_rating::numeric),2)AS "Avg Product Rating"
FROM CUSTOMER
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
limit 5;

--Compare avg purchase amount b/w standard vs express shipping?
select shipping_type,ROUND(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Do subscribed customers spend more? compare avg spend and total revenue between subscribers and non subs
select subscription_status,
count(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,
ROUND(100 * sum(case when discount_applied = 'Yes' THEN 1 ELSE 0 end ) / COUNT(*)) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--segment customers into new,recurring,loyal based on total no of prev purchase and show count of each segment
with customer_type as (
select customer_id,previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
Else 'Loyal'
END AS customer_segment
from customer
)
select customer_segment, count(*) as "No. of Customers"
from customer_type
group by customer_segment

--What are 3 most purchased product within each category?
with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--are customers who are repeat buyers(more than 5 prev purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;